import type { ParsedStep } from './playwright-mcp-agent'

export function compileScript(
  steps: { parsed: ParsedStep; original: string }[],
  baseUrl: string,
  title: string,
): string {
  const lines: string[] = [
    `// Auto-generated by QA Agent — ${new Date().toISOString()}`,
    `// ${title}`,
    ``,
    `import { test, expect } from '@playwright/test'`,
    ``,
    `test('${title.replace(/'/g, "\\'")}', async ({ page }) => {`,
  ]

  for (const { parsed, original } of steps) {
    lines.push(`  // ${original}`)

    const loc = parsed.locator ? resolveLocatorCode(parsed.locator) : null

    switch (parsed.action) {
      case 'navigate': {
        const url = parsed.target.startsWith('http')
          ? parsed.target
          : `${baseUrl}${parsed.target.startsWith('/') ? '' : '/'}${parsed.target}`
        lines.push(`  await page.goto('${url}')`)
        break
      }
      case 'fill':
        if (loc) {
          lines.push(`  await ${loc}.fill('${esc(parsed.value ?? '')}')`)
        } else {
          lines.push(`  await page.getByLabel('${esc(parsed.target)}').fill('${esc(parsed.value ?? '')}')`)
        }
        break
      case 'click':
        if (loc) {
          lines.push(`  await ${loc}.click()`)
        } else {
          lines.push(`  await page.getByRole('button', { name: '${esc(parsed.target)}' }).click()`)
        }
        break
      case 'assert':
        if (parsed.target === 'url') {
          lines.push(`  await expect(page).toHaveURL(/${escapeRegex(parsed.value ?? '')}/)`)
        } else if (loc) {
          lines.push(`  await expect(${loc}).toBeVisible()`)
        } else {
          lines.push(`  await expect(page.getByText('${esc(parsed.target)}', { exact: false })).toBeVisible()`)
        }
        break
      case 'wait':
        if (parsed.target === 'page_load') {
          lines.push(`  await page.waitForLoadState('domcontentloaded')`)
        } else if (loc) {
          lines.push(`  await ${loc}.waitFor()`)
        } else {
          lines.push(`  await page.waitForLoadState('networkidle')`)
        }
        break
    }
  }

  lines.push(`})`)
  return lines.join('\n')
}

function resolveLocatorCode(locator: string): string {
  // locator is already a Playwright expression like page.locator('...') or page.getByRole(...)
  // Strip the leading "page." if present so we can use it as-is
  return locator.startsWith('page.') ? locator : `page.locator('${esc(locator)}')`
}

function esc(s: string) { return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") }
function escapeRegex(s: string) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') }
